/**
 * Exhaustive error code registry for the Secure Exchange Platform.
 * All structured errors must use a code from this enum.
 * Never use ad-hoc string error codes outside this file.
 */
export enum ErrorCode {
  // ── Cryptographic errors ───────────────────────────────────
  CRYPTO_KEY_EXPIRED = 'CRYPTO_KEY_EXPIRED',
  CRYPTO_KEY_NOT_FOUND = 'CRYPTO_KEY_NOT_FOUND',
  CRYPTO_KEY_REVOKED = 'CRYPTO_KEY_REVOKED',
  CRYPTO_KEY_INVALID_STATE = 'CRYPTO_KEY_INVALID_STATE',
  CRYPTO_VERIFICATION_FAILED = 'CRYPTO_VERIFICATION_FAILED',
  CRYPTO_DECRYPTION_FAILED = 'CRYPTO_DECRYPTION_FAILED',
  CRYPTO_ENCRYPTION_FAILED = 'CRYPTO_ENCRYPTION_FAILED',
  CRYPTO_SIGNING_FAILED = 'CRYPTO_SIGNING_FAILED',
  CRYPTO_UNSUPPORTED_ALGORITHM = 'CRYPTO_UNSUPPORTED_ALGORITHM',
  CRYPTO_POLICY_VIOLATION = 'CRYPTO_POLICY_VIOLATION',
  CRYPTO_MISSING_RECIPIENT_KEY = 'CRYPTO_MISSING_RECIPIENT_KEY',
  CRYPTO_MISSING_SIGNING_KEY = 'CRYPTO_MISSING_SIGNING_KEY',
  CRYPTO_CORRUPT_PAYLOAD = 'CRYPTO_CORRUPT_PAYLOAD',

  // ── Transport errors ───────────────────────────────────────
  TRANSPORT_CONNECTION_FAILED = 'TRANSPORT_CONNECTION_FAILED',
  TRANSPORT_AUTH_FAILED = 'TRANSPORT_AUTH_FAILED',
  TRANSPORT_HOST_KEY_MISMATCH = 'TRANSPORT_HOST_KEY_MISMATCH',
  TRANSPORT_TIMEOUT = 'TRANSPORT_TIMEOUT',
  TRANSPORT_UNSUPPORTED_PROTOCOL = 'TRANSPORT_UNSUPPORTED_PROTOCOL',
  TRANSPORT_FILE_NOT_FOUND = 'TRANSPORT_FILE_NOT_FOUND',
  TRANSPORT_PERMISSION_DENIED = 'TRANSPORT_PERMISSION_DENIED',

  // ── Partner rejection errors ───────────────────────────────
  PARTNER_REJECTION = 'PARTNER_REJECTION',
  PARTNER_REJECTION_DUPLICATE = 'PARTNER_REJECTION_DUPLICATE',
  PARTNER_REJECTION_FORMAT = 'PARTNER_REJECTION_FORMAT',
  PARTNER_REJECTION_SCHEMA = 'PARTNER_REJECTION_SCHEMA',
  PARTNER_REJECTION_CUTOFF = 'PARTNER_REJECTION_CUTOFF',

  // ── Validation errors ──────────────────────────────────────
  VALIDATION_SCHEMA_FAILED = 'VALIDATION_SCHEMA_FAILED',
  VALIDATION_DUPLICATE = 'VALIDATION_DUPLICATE',
  VALIDATION_PAYLOAD_TOO_LARGE = 'VALIDATION_PAYLOAD_TOO_LARGE',
  VALIDATION_UNSUPPORTED_CONTENT_TYPE = 'VALIDATION_UNSUPPORTED_CONTENT_TYPE',
  VALIDATION_MISSING_METADATA = 'VALIDATION_MISSING_METADATA',
  VALIDATION_FILENAME_INVALID = 'VALIDATION_FILENAME_INVALID',
  VALIDATION_CHECKSUM_MISMATCH = 'VALIDATION_CHECKSUM_MISMATCH',
  VALIDATION_MALWARE_DETECTED = 'VALIDATION_MALWARE_DETECTED',
  VALIDATION_DECOMPRESSION_BOMB = 'VALIDATION_DECOMPRESSION_BOMB',
  VALIDATION_MAGIC_BYTES_MISMATCH = 'VALIDATION_MAGIC_BYTES_MISMATCH',

  // ── Policy errors ──────────────────────────────────────────
  POLICY_ENVIRONMENT_MISMATCH = 'POLICY_ENVIRONMENT_MISMATCH',
  POLICY_PROFILE_INACTIVE = 'POLICY_PROFILE_INACTIVE',
  POLICY_PROFILE_SUSPENDED = 'POLICY_PROFILE_SUSPENDED',
  POLICY_RETRY_LIMIT_EXCEEDED = 'POLICY_RETRY_LIMIT_EXCEEDED',
  POLICY_RETENTION_DENIED = 'POLICY_RETENTION_DENIED',

  // ── Access control errors ──────────────────────────────────
  RBAC_INSUFFICIENT_ROLE = 'RBAC_INSUFFICIENT_ROLE',
  RBAC_RESOURCE_NOT_FOUND = 'RBAC_RESOURCE_NOT_FOUND',
  TENANT_BOUNDARY_VIOLATION = 'TENANT_BOUNDARY_VIOLATION',
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED = 'TENANT_SUSPENDED',
  // Programming bugs — caller must provide a tenant context for tenant-scoped DB access
  TENANT_CONTEXT_MISSING = 'TENANT_CONTEXT_MISSING',
  TENANT_CONTEXT_INVALID = 'TENANT_CONTEXT_INVALID',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_API_KEY_INVALID = 'AUTH_API_KEY_INVALID',

  // ── Approval / workflow errors ─────────────────────────────
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  APPROVAL_ALREADY_PENDING = 'APPROVAL_ALREADY_PENDING',
  APPROVAL_EXPIRED = 'APPROVAL_EXPIRED',
  APPROVAL_SELF_APPROVAL_FORBIDDEN = 'APPROVAL_SELF_APPROVAL_FORBIDDEN',
  APPROVAL_INSUFFICIENT_ROLE = 'APPROVAL_INSUFFICIENT_ROLE',

  // ── Key management errors ──────────────────────────────────
  KEY_ROTATION_CONFLICT = 'KEY_ROTATION_CONFLICT',
  KEY_ROTATION_NOT_ACTIVE = 'KEY_ROTATION_NOT_ACTIVE',
  KEY_IMPORT_INVALID = 'KEY_IMPORT_INVALID',
  KEY_FINGERPRINT_MISMATCH = 'KEY_FINGERPRINT_MISMATCH',
  KEY_BACKEND_UNAVAILABLE = 'KEY_BACKEND_UNAVAILABLE',

  // ── Submission lifecycle errors ────────────────────────────
  SUBMISSION_NOT_FOUND = 'SUBMISSION_NOT_FOUND',
  SUBMISSION_TERMINAL_STATE = 'SUBMISSION_TERMINAL_STATE',
  SUBMISSION_NOT_RETRYABLE = 'SUBMISSION_NOT_RETRYABLE',
  SUBMISSION_CORRELATION_NOT_FOUND = 'SUBMISSION_CORRELATION_NOT_FOUND',
  SUBMISSION_PAYLOAD_TAMPERED = 'SUBMISSION_PAYLOAD_TAMPERED',
  SUBMISSION_SCAN_UNAVAILABLE = 'SUBMISSION_SCAN_UNAVAILABLE',
  SUBMISSION_QUARANTINED = 'SUBMISSION_QUARANTINED',

  // ── Delivery errors ───────────────────────────────────────
  DELIVERY_ENDPOINT_BLOCKED = 'DELIVERY_ENDPOINT_BLOCKED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',

  // ── Inbound errors ────────────────────────────────────────
  INBOUND_VERIFICATION_FAILED = 'INBOUND_VERIFICATION_FAILED',
  INBOUND_VERIFICATION_SKIPPED = 'INBOUND_VERIFICATION_SKIPPED',

  // ── Infrastructure errors ──────────────────────────────────
  STORAGE_UPLOAD_FAILED = 'STORAGE_UPLOAD_FAILED',
  STORAGE_DOWNLOAD_FAILED = 'STORAGE_DOWNLOAD_FAILED',
  STORAGE_OBJECT_NOT_FOUND = 'STORAGE_OBJECT_NOT_FOUND',
  QUEUE_PUBLISH_FAILED = 'QUEUE_PUBLISH_FAILED',
  DATABASE_ERROR = 'DATABASE_ERROR',

  // ── Replay protection ──────────────────────────────────────
  REPLAY_NONCE_REUSED = 'REPLAY_NONCE_REUSED',
  REPLAY_TIMESTAMP_OUTSIDE_WINDOW = 'REPLAY_TIMESTAMP_OUTSIDE_WINDOW',

  // ── Internal errors ────────────────────────────────────────
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
}

/** Errors that should never be retried — fail closed permanently */
export const TERMINAL_ERROR_CODES = new Set<ErrorCode>([
  ErrorCode.CRYPTO_KEY_EXPIRED,
  ErrorCode.CRYPTO_KEY_INVALID_STATE,
  ErrorCode.CRYPTO_VERIFICATION_FAILED,
  ErrorCode.CRYPTO_POLICY_VIOLATION,
  ErrorCode.CRYPTO_UNSUPPORTED_ALGORITHM,
  ErrorCode.TRANSPORT_HOST_KEY_MISMATCH,
  ErrorCode.TRANSPORT_AUTH_FAILED,
  ErrorCode.VALIDATION_MALWARE_DETECTED,
  ErrorCode.VALIDATION_DUPLICATE,
  ErrorCode.POLICY_ENVIRONMENT_MISMATCH,
  ErrorCode.POLICY_PROFILE_INACTIVE,
  ErrorCode.POLICY_PROFILE_SUSPENDED,
  ErrorCode.POLICY_RETRY_LIMIT_EXCEEDED,
  ErrorCode.TENANT_BOUNDARY_VIOLATION,
  ErrorCode.TENANT_CONTEXT_MISSING,
  ErrorCode.TENANT_CONTEXT_INVALID,
  ErrorCode.APPROVAL_SELF_APPROVAL_FORBIDDEN,
  ErrorCode.REPLAY_NONCE_REUSED,
  ErrorCode.SUBMISSION_PAYLOAD_TAMPERED,
  ErrorCode.SUBMISSION_QUARANTINED,
  ErrorCode.DELIVERY_ENDPOINT_BLOCKED,
  ErrorCode.INBOUND_VERIFICATION_FAILED,
  ErrorCode.VALIDATION_DECOMPRESSION_BOMB,
  ErrorCode.VALIDATION_MAGIC_BYTES_MISMATCH,
  ErrorCode.INBOUND_VERIFICATION_SKIPPED,
]);

/** Errors that are safe to retry with backoff */
export const RETRYABLE_ERROR_CODES = new Set<ErrorCode>([
  ErrorCode.TRANSPORT_CONNECTION_FAILED,
  ErrorCode.TRANSPORT_TIMEOUT,
  ErrorCode.TRANSPORT_FILE_NOT_FOUND,
  ErrorCode.KEY_BACKEND_UNAVAILABLE,
  ErrorCode.STORAGE_UPLOAD_FAILED,
  ErrorCode.STORAGE_DOWNLOAD_FAILED,
  ErrorCode.QUEUE_PUBLISH_FAILED,
]);
