/**
 * Per-scenario tenant cuid registry (M3.A8).
 *
 * Each scenario gets its own pair of tenant IDs so a test that
 * leaves state behind (lockouts, audit rows, quota counters) can't
 * contaminate another scenario. Cuids are fixed (not random) so the
 * Redis + Postgres keys generated by each scenario are reproducible
 * across runs and easy to grep in a failing CI log.
 *
 * ensureThreatTestTenants() is idempotent (upsert) and is called at
 * the start of each scenario's suite. No teardown — tenants persist
 * across runs; per-test cleanup removes only the rows the scenario
 * seeded.
 */

import type { PrismaClient } from '@prisma/client';

// Fixed cuids. Shape: 'c' + lowercase alnum, 25-27 chars. Must pass
// CuidSchema.safeParse from @sep/schemas.
export const TENANTS = Object.freeze({
  T01_stolen_credential_owner: 'cthreatsc01stolenownr0001',
  T01_stolen_credential_other: 'cthreatsc01stolenothr0001',
  T02_misrouted_owner: 'cthreatsc02misroutedown01',
  T03_wrong_key_owner: 'cthreatsc03wrongkeyown001',
  T03_wrong_key_other: 'cthreatsc03wrongkeyotr001',
  T04_expired_key_owner: 'cthreatsc04expiredown0001',
  T05_idempotency_owner: 'cthreatsc05idempownr00001',
  T06_tampered_ack_owner: 'cthreatsc06tamperownr0001',
  T07_log_secret_owner: 'cthreatsc07logsecretown01',
  T08_cross_tenant_victim: 'cthreatsc08xtnvictim00001',
  T08_cross_tenant_attacker: 'cthreatsc08xtnattack00001',
  T09_unauth_profile_owner: 'cthreatsc09unauthown00001',
  T10_ssrf_owner: 'cthreatsc10ssrfowner00001',
  T11_rotation_owner: 'cthreatsc11rotationown001',
  T12_refresh_replay_owner: 'cthreatsc12refreshown0001',
  T13_brute_force_owner: 'cthreatsc13bruteforceown1',
  T14_audit_tamper_owner: 'cthreatsc14audittamperow1',
});

export type ThreatTenantKey = keyof typeof TENANTS;

/**
 * Upsert the specified tenants. Each scenario's setup calls this
 * with the subset it cares about; we upsert the full set at the
 * suite level (cheap) rather than per-file to keep startup uniform.
 */
export async function ensureThreatTestTenants(
  seed: PrismaClient,
  keys: readonly ThreatTenantKey[] = Object.keys(TENANTS) as ThreatTenantKey[],
): Promise<void> {
  for (const key of keys) {
    const id = TENANTS[key];
    // eslint-disable-next-line no-await-in-loop -- intentional serial upserts
    await seed.tenant.upsert({
      where: { id },
      update: {},
      create: {
        id,
        name: `Threat-Scenario ${key}`,
        legalEntityName: `Threat-Scenario ${key} LLC`,
      },
    });
  }
}
